### ISSUE TITLE
challenge reaching low power levels

### ISSUE THREAD

**Issue by jerabaul29** [adafruit/Adafruit-Trinket-PCB#1]
I know this is depreciated, but I just wanted to report / discuss some findings about the behavior of the board in low power applications. The reason why I ordered it in the first place was because I wanted to be able to have some super low power consumption during sleep. However, this did not work, as reported in this issue:

https://arduino.stackexchange.com/questions/39432/cannot-get-low-power-with-adafruit-trinket/77114?noredirect=1#comment169885_77114

It looks like the culprit is a diode + resistor on a USB port pin (this is a copy of the text in the linked issue):

"
The USB connector uses a resistor (1500 Ohms) against the 5V net and a 3.6 Volt Z-Diode on it's (D-)-Pin. In addition to the current that is drawn by the microcontroller, this part of the circuit draws some extra current. (5[V] - 3.6[V])/1500[ohm] = 0.0009333... ~= 0.001 [A].

Even though I'm not completely sure without making some tests, that seams plausible to me.

EDIT (Answer to the OPs comment below.)

The schematics uses a normal diode symbol but has a 3.6 Volt label next to it. I assume that it should be a Zener diode with a reverse voltage drop of 3.6 Volts. If I'm right, the Diode is used to limit the 5 Volts to 3.6 Volts (for what reason ever). The Zener Diode effectively limits the Voltage over it to 3.6 Volts. The rest of the voltage of 5 Volts must be dropped over the resistor. i.e. 5V - 3.6V = 1.4V. This voltage drop tells us by Ohms Law that the current through the resistor is:

```
I = U / R
I[A] = 1.4[V] / 1500[Ohm]  = (about) 1 mA.
```

This value is very reasonable for your observations and the current is drawn from the 5V connect, hence you can measure it, even if you would desolder the microcontroller.
"

- Can you confirm that this is well the cause?

- I am just curious: why was this setup used?

- Can you / maybe you should add some warnings / documentation about this, so that other 'naive' users like me who would like to achieve very low power from a simple development board do not choose this board / fall in the trap? :)

**Comment by ladyada** [comment]
this is a simple, low cost level shifter for the USB pins so they are 5V. the 3V trinket does not have them

**Comment by jerabaul29** [comment]
Thanks for the quick reply :) Ok, understood :) .
